image: docker:latest
services: 
  - name: docker:dind
    alias: docker

stages: 
  - Build image
  - Test acceptation
  - Release image
  
build:
  stage: Build image
  script:
    - docker build -t alpinehelloworld .
    - docker save alpinehelloworld > alpinehelloworld.tar
  artifacts: 
    paths: 
      - alpinehelloworld.tar

test acceptation: 
  stage: Test acceptation
  script: 
    - docker load < alpinehelloworld.tar
    - docker run -d -p 80:5000 --env PORT=5000 --name webapp alpinehelloworld
    - sleep 5
    - apk --no-cache add curl 
    - curl "http://docker" | grep -q "Hello world!"

release image: 
  stage: Release image
  script: 
    - docker load < alpinehelloworld.tar
    - docker tag alpinehelloworld "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag alpinehelloworld "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
