stages: 
  - Build image
  - Test acceptation
  
build:
  image: docker:latest
  stage: Build image
  services:
    - docker:dind
  script:
    - docker build -t alpinehelloworld .

test acceptation: 
  image: docker:latest  
  stage: Test acceptation
  services: 
    - docker:dind
  script: 
    - docker run -d --name webapp alpinehelloworld
