stages: 
  - Build image
  - Test acceptation
  
build:
  image: docker:latest
  stage: Build image
  services:
    - docker:dind
  script:
    - docker build -t alpinehelloworld .
    - docker save alpinehelloworld > alpinehelloworld.tar
  artifacts: 
    paths: 
      - alpihehelloworld.tar

test acceptation: 
  image: docker:latest  
  stage: Test acceptation
  services: 
    - docker:dind
  script: 
    - docker load < alpihehelloworld.tar
    - docker run -d --name webapp alpinehelloworld
